# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_retrieval.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data_retrieval.proto',
  package='com.data.retrieval',
  syntax='proto3',
  serialized_pb=_b('\n\x14\x64\x61ta_retrieval.proto\x12\x12\x63om.data.retrieval\"A\n\x0c\x45mployeeList\x12\x0e\n\x06\x65mp_id\x18\x01 \x03(\x05\x12\x0c\n\x04name\x18\x02 \x03(\t\x12\x13\n\x0b\x64\x65signation\x18\x03 \x03(\t\"=\n\x08\x45mployee\x12\x0e\n\x06\x65mp_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65signation\x18\x03 \x01(\t\"\x1a\n\x0bResponseMsg\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x1a\n\x07Version\x12\x0f\n\x07version\x18\x01 \x01(\t2\xa6\x01\n\x0c\x44\x61taRetrival\x12J\n\x07setData\x12\x1c.com.data.retrieval.Employee\x1a\x1f.com.data.retrieval.ResponseMsg\"\x00\x12J\n\x07getData\x12\x1b.com.data.retrieval.Version\x1a .com.data.retrieval.EmployeeList\"\x00\x62\x06proto3')
)




_EMPLOYEELIST = _descriptor.Descriptor(
  name='EmployeeList',
  full_name='com.data.retrieval.EmployeeList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='emp_id', full_name='com.data.retrieval.EmployeeList.emp_id', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='com.data.retrieval.EmployeeList.name', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='designation', full_name='com.data.retrieval.EmployeeList.designation', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=109,
)


_EMPLOYEE = _descriptor.Descriptor(
  name='Employee',
  full_name='com.data.retrieval.Employee',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='emp_id', full_name='com.data.retrieval.Employee.emp_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='com.data.retrieval.Employee.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='designation', full_name='com.data.retrieval.Employee.designation', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=172,
)


_RESPONSEMSG = _descriptor.Descriptor(
  name='ResponseMsg',
  full_name='com.data.retrieval.ResponseMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='com.data.retrieval.ResponseMsg.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=200,
)


_VERSION = _descriptor.Descriptor(
  name='Version',
  full_name='com.data.retrieval.Version',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='com.data.retrieval.Version.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=228,
)

DESCRIPTOR.message_types_by_name['EmployeeList'] = _EMPLOYEELIST
DESCRIPTOR.message_types_by_name['Employee'] = _EMPLOYEE
DESCRIPTOR.message_types_by_name['ResponseMsg'] = _RESPONSEMSG
DESCRIPTOR.message_types_by_name['Version'] = _VERSION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmployeeList = _reflection.GeneratedProtocolMessageType('EmployeeList', (_message.Message,), dict(
  DESCRIPTOR = _EMPLOYEELIST,
  __module__ = 'data_retrieval_pb2'
  # @@protoc_insertion_point(class_scope:com.data.retrieval.EmployeeList)
  ))
_sym_db.RegisterMessage(EmployeeList)

Employee = _reflection.GeneratedProtocolMessageType('Employee', (_message.Message,), dict(
  DESCRIPTOR = _EMPLOYEE,
  __module__ = 'data_retrieval_pb2'
  # @@protoc_insertion_point(class_scope:com.data.retrieval.Employee)
  ))
_sym_db.RegisterMessage(Employee)

ResponseMsg = _reflection.GeneratedProtocolMessageType('ResponseMsg', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEMSG,
  __module__ = 'data_retrieval_pb2'
  # @@protoc_insertion_point(class_scope:com.data.retrieval.ResponseMsg)
  ))
_sym_db.RegisterMessage(ResponseMsg)

Version = _reflection.GeneratedProtocolMessageType('Version', (_message.Message,), dict(
  DESCRIPTOR = _VERSION,
  __module__ = 'data_retrieval_pb2'
  # @@protoc_insertion_point(class_scope:com.data.retrieval.Version)
  ))
_sym_db.RegisterMessage(Version)



_DATARETRIVAL = _descriptor.ServiceDescriptor(
  name='DataRetrival',
  full_name='com.data.retrieval.DataRetrival',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=231,
  serialized_end=397,
  methods=[
  _descriptor.MethodDescriptor(
    name='setData',
    full_name='com.data.retrieval.DataRetrival.setData',
    index=0,
    containing_service=None,
    input_type=_EMPLOYEE,
    output_type=_RESPONSEMSG,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getData',
    full_name='com.data.retrieval.DataRetrival.getData',
    index=1,
    containing_service=None,
    input_type=_VERSION,
    output_type=_EMPLOYEELIST,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATARETRIVAL)

DESCRIPTOR.services_by_name['DataRetrival'] = _DATARETRIVAL

# @@protoc_insertion_point(module_scope)
