# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import number_ops_pb2 as number__ops__pb2


class DataRetrivalStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.inputData = channel.unary_unary(
        '/com.number.operation.DataRetrival/inputData',
        request_serializer=number__ops__pb2.InputNos.SerializeToString,
        response_deserializer=number__ops__pb2.Output.FromString,
        )


class DataRetrivalServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def inputData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DataRetrivalServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'inputData': grpc.unary_unary_rpc_method_handler(
          servicer.inputData,
          request_deserializer=number__ops__pb2.InputNos.FromString,
          response_serializer=number__ops__pb2.Output.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'com.number.operation.DataRetrival', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
