# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: number_ops.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='number_ops.proto',
  package='com.number.operation',
  syntax='proto3',
  serialized_pb=_b('\n\x10number_ops.proto\x12\x14\x63om.number.operation\" \n\x08InputNos\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"N\n\x06Output\x12\x0f\n\x07square1\x18\x01 \x01(\x05\x12\x0f\n\x07square2\x18\x02 \x01(\x05\x12\x10\n\x08\x61\x64\x64ition\x18\x03 \x01(\x05\x12\x10\n\x08multiply\x18\x04 \x01(\x05\x32[\n\x0c\x44\x61taRetrival\x12K\n\tinputData\x12\x1e.com.number.operation.InputNos\x1a\x1c.com.number.operation.Output\"\x00\x62\x06proto3')
)




_INPUTNOS = _descriptor.Descriptor(
  name='InputNos',
  full_name='com.number.operation.InputNos',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='com.number.operation.InputNos.a', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None ),
    _descriptor.FieldDescriptor(
      name='b', full_name='com.number.operation.InputNos.b', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None ),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=74,
)


_OUTPUT = _descriptor.Descriptor(
  name='Output',
  full_name='com.number.operation.Output',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='square1', full_name='com.number.operation.Output.square1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None ),
    _descriptor.FieldDescriptor(
      name='square2', full_name='com.number.operation.Output.square2', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None ),
    _descriptor.FieldDescriptor(
      name='addition', full_name='com.number.operation.Output.addition', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None ),
    _descriptor.FieldDescriptor(
      name='multiply', full_name='com.number.operation.Output.multiply', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None ),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=154,
)

DESCRIPTOR.message_types_by_name['InputNos'] = _INPUTNOS
DESCRIPTOR.message_types_by_name['Output'] = _OUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InputNos = _reflection.GeneratedProtocolMessageType('InputNos', (_message.Message,), dict(
  DESCRIPTOR = _INPUTNOS,
  __module__ = 'number_ops_pb2'
  # @@protoc_insertion_point(class_scope:com.number.operation.InputNos)
  ))
_sym_db.RegisterMessage(InputNos)

Output = _reflection.GeneratedProtocolMessageType('Output', (_message.Message,), dict(
  DESCRIPTOR = _OUTPUT,
  __module__ = 'number_ops_pb2'
  # @@protoc_insertion_point(class_scope:com.number.operation.Output)
  ))
_sym_db.RegisterMessage(Output)



_DATARETRIVAL = _descriptor.ServiceDescriptor(
  name='DataRetrival',
  full_name='com.number.operation.DataRetrival',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=156,
  serialized_end=247,
  methods=[
  _descriptor.MethodDescriptor(
    name='inputData',
    full_name='com.number.operation.DataRetrival.inputData',
    index=0,
    containing_service=None,
    input_type=_INPUTNOS,
    output_type=_OUTPUT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATARETRIVAL)

DESCRIPTOR.services_by_name['DataRetrival'] = _DATARETRIVAL

# @@protoc_insertion_point(module_scope)
